server:
  port: 8888

spring:
  application:
    name: orange-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Magicanshowszz/orange-parent
          search-paths: orange-config-repo
          username: 404869355@qq.com
          password: q139556
      label: master

#spring:
#  application:
#    name: orange-config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://gitee.com/zzsong/orange-config-repo
#          username: 404869355@qq.com
#          password: q139556
#      label: master

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka #,http://user:password123@localhost:8762/eureka
    eureka-server-connect-timeout-seconds: 30
